apiVersion: v1
kind: Service
metadata:
  name: dcr-headless
  annotations:
    # Hooks are added to ensure that:
    #   - The DCR related ressources are created before the job is executed
    #   - The job is executed before the main chart is installed, upgraded or synced
    #   - ArgoCD does not expect the job to exist after it's execution
    #   - The DCR related ressources and the DCR job are created or executed before any other hook (if any)
    #   - The job is deleted if it still exists when the chart is upgraded or uninstalled
    # ArgoCD hook
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
    # Helm hook
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  clusterIP: None
  selector:
    job-name: dcr
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dcr
  annotations:
    # ArgoCD hook
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
    # Helm hook
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  register.sh: |
{{ .Files.Get "scripts/register.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dcr
  labels:
    app: dcr
  annotations:
    # ArgoCD hooks
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
    # Helm hooks
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: {{ .Values.ttl_seconds }}
  template:
    spec:
      containers:
        - name: register
          image: {{ .Values.image }}
          command: ["/bin/sh", "/mnt/dcr/register.sh"]
          env:
            - name: SECRET_NAME
              value: {{ include "secret.name" . | quote }}
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: DCR_REGISTRATION_URL
              value: {{ .Values.registration_url | quote }}
            - name: REQUEST
              value: {{ .Values.request | toJson | quote }}
            - name: SECRET_KEYS
              value: {{ include "secret.keys" . | fromYaml | toJson | quote }}
            - name: CURL_OPTION
              {{- if .Values.tls.insecure }}
              value: "-sk"
              {{- else }}
              value: "-s"
              {{- end }}
            {{- if (ne .Values.tls.certificate "") }}
            - name: TLS_CERTIFICATE
              value: {{ .Values.tls.certificate | quote }}
            {{- end }}
          volumeMounts:
            - name: dcr-volume
              mountPath: /mnt/dcr
              {{- if include "volume_mount.secret" . }}
              {{- include "volume_mount.secret" . | nindent 12 -}}
              {{- end }}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      serviceAccountName: {{ include "service_account.name" . }}
      volumes:
        - name: dcr-volume
          configMap:
            defaultMode: 493
            name: dcr
        {{- if include "volume.secret" . }}
        {{- include "volume.secret" . | nindent 8 -}}
        {{- end }}
      restartPolicy: Never
