apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcr.headless" . }}
  {{- with .Values.common_labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
{{ include "hooks.ressources" . | indent 4 }}
spec:
  clusterIP: None
  selector:
    job-name: {{ include "dcr.name" . }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dcr.name" . }}
  {{- with .Values.common_labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
{{ include "hooks.ressources" . | indent 4 }}
data:
  register.sh: |
{{ .Files.Get "scripts/register.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dcr.name" . }}
  labels:
    {{- toYaml (merge (deepCopy .Values.common_labels) (dict "app" "dcr")) | nindent 4 }}
  annotations:
{{ include "hooks.job" . | indent 4 }}
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: {{ .Values.ttl_seconds }}
  template:
    {{- with .Values.common_labels }}
    metadata:
      labels:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: register
          image: {{ include "image" . | quote }}
          imagePullPolicy: {{ .Values.image.pull_policy }}
          command: ["/bin/sh", "/mnt/dcr/register.sh"]
          env:
            - name: SECRET_NAME
              value: {{ include "secret.name" . | quote }}
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: DCR_REGISTRATION_URL
              value: {{ .Values.registration_url | quote }}
            - name: REQUEST
              value: {{ .Values.request | toJson | quote }}
            - name: SECRET_KEYS
              value: {{ include "secret.keys" . | fromYaml | toJson | quote }}
            - name: CURL_OPTION
              {{- if .Values.tls.insecure }}
              value: "-sk"
              {{- else }}
              value: "-s"
              {{- end }}
            {{- if (ne .Values.tls.certificate "") }}
            - name: TLS_CERTIFICATE
              value: {{ .Values.tls.certificate | quote }}
            {{- end }}
          volumeMounts:
            - name: dcr-volume
              mountPath: /mnt/dcr
              {{- if include "volume_mount.secret" . }}
              {{- include "volume_mount.secret" . | nindent 12 -}}
              {{- end }}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      serviceAccountName: {{ include "service_account.name" . }}
      {{- with .Values.image.pull_secrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      volumes:
        - name: dcr-volume
          configMap:
            defaultMode: 493
            name: {{ include "dcr.name" . }}
        {{- if include "volume.secret" . }}
        {{- include "volume.secret" . | nindent 8 -}}
        {{- end }}
      restartPolicy: Never
